services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    expose:
      - "5000"
    restart: always
    networks:
      - app

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
    networks:
      - app

networks:
  app:
    driver: bridge
